- platform: rest
  resource: !secret esp_poele_temp
  name: "Ext. Temperature"
  value_template: '{{ float(value_json.temperature) }}'
  unit_of_measurement: "°C"
  scan_interval: 300
#- platform: yr
- platform: onewire
  names:
      28-80000003e85b: "Int."
  scan_interval: 300
- platform: darksky
  api_key: ea0f9adbb1b6e010b7c1ae76543334e3
  forecast: [1]
  monitored_conditions:
    - icon
    - temperature_max
    - temperature_min
- platform: template
  sensors:
    today_meteo:
      friendly_name: "Météo"
      value_template: ""
      entity_picture_template: "/local/darksky/{{ states('sensor.dark_sky_icon') }}.png"
    demain_meteo:
      friendly_name: "Météo"
      value_template: ""
      entity_picture_template: "/local/darksky/{{ states('sensor.dark_sky_icon_1') }}.png"